// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-degree-paths.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var DEGREE_DOMAINS = [
  { id: "btech", label: "B.Tech \u2013 Degree" },
  { id: "bsc", label: "B.Sc \u2013 Degree" },
  { id: "diploma", label: "Diploma" },
  { id: "integrated", label: "Integrated Course" }
];
var SUBJECT_COMBINATIONS = {
  MPC: ["Math", "Physics", "Chemistry"],
  MBIPC: ["Math", "Biology", "Physics", "Chemistry"],
  BIPC: ["Biology", "Physics", "Chemistry"]
};
var list_degree_paths_default = defineTool({
  name: "list_degree_paths",
  title: "List degree paths",
  description: "List the undergraduate degree domains and 11th/12th subject combinations covered by Undergraduate Maps.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({ domains: DEGREE_DOMAINS, subjectCombinations: SUBJECT_COMBINATIONS }, null, 2)
      }
    ],
    structuredContent: { domains: DEGREE_DOMAINS, subjectCombinations: SUBJECT_COMBINATIONS }
  })
});

// src/lib/mcp/tools/explore-careers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var BRANCHES = [
  {
    id: "ece",
    name: "Electronics & Communication (ECE)",
    overview: "Circuits, embedded systems, signal processing, and communication networks.",
    coreRoles: ["Embedded Engineer", "VLSI Design Engineer", "RF Engineer", "IoT Developer"],
    realityCheck: "Core electronics jobs are limited and competitive; many graduates move into IT/software roles."
  },
  {
    id: "mechanical",
    name: "Mechanical Engineering",
    overview: "Design, manufacturing, thermodynamics, and mechanical systems.",
    coreRoles: ["Design Engineer", "Production Engineer", "CAD/CAM Engineer", "Quality Engineer"],
    realityCheck: "Entry salaries in core industry are often modest; growth depends on domain specialization."
  },
  {
    id: "civil",
    name: "Civil Engineering",
    overview: "Structures, construction, transportation, and infrastructure.",
    coreRoles: ["Site Engineer", "Structural Engineer", "Project Engineer", "Surveyor"],
    realityCheck: "Fieldwork is demanding with long hours; government exams are a common stable path."
  },
  {
    id: "cse",
    name: "Computer Science / IT",
    overview: "Software development, data, and computing systems.",
    coreRoles: ["Software Engineer", "Data Analyst", "DevOps Engineer", "Full-Stack Developer"],
    realityCheck: "Highest hiring volume, but the market is saturated at entry level; skills matter more than the degree."
  }
];
var explore_careers_default = defineTool2({
  name: "explore_careers",
  title: "Explore careers",
  description: "Explore engineering branches with an honest overview, core job roles, and a reality check. Optionally filter by branch id.",
  inputSchema: {
    branchId: z.enum(["ece", "mechanical", "civil", "cse"]).optional().describe("Optional branch id to filter to a single branch.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ branchId }) => {
    const result = branchId ? BRANCHES.filter((b) => b.id === branchId) : BRANCHES;
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { branches: result }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "undergraduate-maps-mcp",
  title: "Undergraduate Maps MCP",
  version: "0.1.0",
  instructions: "Tools for Undergraduate Maps, a career-and-degree guidance app for Indian students. Use `list_degree_paths` to see degree domains and subject combinations, and `explore_careers` to get honest overviews, job roles, and reality checks for engineering branches.",
  tools: [list_degree_paths_default, explore_careers_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
